# Generated by Django 3.1.5 on 2021-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210128_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_likes',
        ),
        migrations.AddField(
            model_name='story',
            name='story_award_winning_place',
            field=models.CharField(default='Неизвестно', max_length=200, verbose_name='Призовое место'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_competition',
            field=models.CharField(default='Неизвестно', max_length=200, verbose_name='Название конкурса'),
        ),
    ]
