# Generated by Django 3.1.5 on 2021-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210204_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_competition_description',
            field=models.CharField(default='Неизвестно', max_length=500, verbose_name='Описание конкурса'),
        ),
    ]
