# Generated by Django 3.1.5 on 2021-01-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210128_1710'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagehit',
            options={'verbose_name': 'Счётчик', 'verbose_name_plural': 'Счётчики'},
        ),
        migrations.AddField(
            model_name='pagehit',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story'),
        ),
    ]
