# Generated by Django 3.1.5 on 2021-01-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210128_1710'),
        ('analytics', '0002_auto_20210128_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehit',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story'),
        ),
    ]
