# Generated by Django 3.1.5 on 2021-01-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20210128_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagehit',
            name='story',
        ),
    ]
